### ISSUE TITLE
Interrupt busDefinition

### ISSUE THREAD

**Issue by Ramlakshmi3733** [sifive/duh-bus#30]
We have to add a clock association and power association to interrupt interface.
From the Synopsys DW_I2C IP:Table 4-1
 Interrupts Signals
Port Name
ic_intr(_n)
I/O Description
O
Optional. Combined interrupt. This signal is included on the interface
when the configuration parameter IC_INTR_IO is unchecked (0) to
indicate that only one interrupt line appears on the I/O (as opposed to
individual interrupt signals).
Exists: IC_INTR_IO == 1
Synchronous To: pclk
Registered: Yes
Power Domain: SINGLE_DOMAIN
Active State: High when IC_INTR_POL=1 otherwise Low

**Comment by drom** [comment]
here: https://github.com/sifive/duh-bus/blob/master/specs/sifive.com/PRCI/INTERRUPT/0.1.0/INTERRUPT_rtl.json5
